### ISSUE TITLE
version 4.0.0 aot doesn't work when assigning something to `(update)` event

### ISSUE THREAD

**Issue by ronzeidman** [plantain-00/select2-component#19]
#### Environment(if relevant):
Angular 5.0.0 Rxjs 5.5.2

#### Code(if relevant):
assigning something to `(update)` event in the template

#### Expected:
work
#### Actual:
main.module.chunk.js:1316 ERROR TypeError: Cannot read property 'subscribe' of undefined

Seems like the use of typescript@2.6.1 is the issue (ngc does not support it...) seems to be working OK with typescript 2.4.2 though. (ngc for some reason will remove the update property from the class in typescript 2.6.1)
Another issue is the use of `import { Subject } from "rxjs";` if you use `import { Subject } from "rxjs/Subject"` it will get just the Subject, this works better with the new "lettables" of rxjs 5.5

**Comment by plantain-00** [comment]
v4.0.1 should fix the 2 issues.

**Comment by ronzeidman** [comment]
Thanks! Working
